### ISSUE TITLE
observe on main thread?

### ISSUE THREAD

**Issue by broakenmedia** [pakoito/RxPaper2#1]
```
Single<List<String>> read = rxPaperBook.read(PAPER_BOOK_CART_KEY);
        read.observeOn(AndroidSchedulers.mainThread());
        read.subscribe(new SingleObserver<List<String>>() {
...
```

Is erroring out that i'm trying to change the UI off the main thread. I'm fairly new to RxJava is there anything i'm missing?

**Comment by pakoito** [comment]
I'd like to see what the error is! Do you have a stacktrace?

**Comment by broakenmedia** [comment]
> Only the original thread that created a view hierarchy can touch its views.

That's about all i've got sorry! The error is happening because i'm trying to update my UI from the success callback, but the callback is not on the Main Thread despite me setting the observeOn. There's no log errors from the library itself, i was hoping i'd simply set it up wrong!

**Comment by broakenmedia** [comment]
```
06-29 00:23:08.307 15158-15312/app.i_do W/System.err:     at app.i_do.main.Checkout$10.onSuccess(Checkout.java:466)
06-29 00:23:08.307 15158-15312/app.i_do W/System.err:     at app.i_do.main.Checkout$10.onSuccess(Checkout.java:459)
06-29 00:23:08.307 15158-15312/app.i_do W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)
06-29 00:23:08.307 15158-15312/app.i_do W/System.err:     at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:37)
06-29 00:23:08.307 15158-15312/app.i_do W/System.err:     at io.reactivex.Single.subscribe(Single.java:2692)
06-29 00:23:08.307 15158-15312/app.i_do W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
06-29 00:23:08.307 15158-15312/app.i_do W/System.err:     at io.reactivex.Scheduler$1.run(Scheduler.java:138)
06-29 00:23:08.307 15158-15312/app.i_do W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
06-29 00:23:08.307 15158-15312/app.i_do W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
06-29 00:23:08.307 15158-15312/app.i_do W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-29 00:23:08.307 15158-15312/app.i_do W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
06-29 00:23:08.307 15158-15312/app.i_do W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-29 00:23:08.307 15158-15312/app.i_do W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-29 00:23:08.307 15158-15312/app.i_do W/System.err:     at java.lang.Thread.run(Thread.java:761)
```

**Comment by pakoito** [comment]
Oh man, I see it now.

```
Single<List<String>> read = rxPaperBook.read(PAPER_BOOK_CART_KEY)
.observeOn(AndroidSchedulers.mainThread())
.subscribe(new SingleObserver<List<String>>() {
```

Lemme explain: Observables are descriptions of what's going to happen. Every time you add a new operator, the underlaying description doesn't change, instead it gives you a new one. In other words, it doesn't *mutate* the origin.

On your code, on the second line, you create an Observable that goes to the main thread, and don't set it to any variable. On line 3 you take the original Observable without the main thread changes, and run it. Obv it complains that the op is still on the original thread because your line 2 never mutated the origin.

On my example I chain the description instead, that should work.

Good coding!

**Comment by broakenmedia** [comment]
Ah man, thanks for that! Shouldn't code so late! I seem to however not be able to get that working either!

http://i.imgur.com/napObHQ.png

If i simply set like so:

```
Single<List<String>> read = rxPaperBook.read(PAPER_BOOK_CART_KEY)
                .observeOn(AndroidSchedulers.mainThread());
```

It tries to force me to have Single<Object> instead

**Comment by broakenmedia** [comment]
Not to worry, it looks like i've gotten it to work... Feels fairly silly though haha.

```
Single<List<String>> read = rxPaperBook.read(PAPER_BOOK_CART_KEY);
read = read.observeOn(AndroidSchedulers.mainThread());
read.subscribe(...
```

Thank you very much for your help, from one stranger to another :) Great work on the lib

**Comment by pakoito** [comment]
Cheers! I'll close the issue now.
