### ISSUE TITLE
Conflict with dependency Objenesis 2.2

### ISSUE THREAD

**Issue by danieldisu** [pakoito/RxPaper2#3]
After including the dependency it throws the following error 

Error:Conflict with dependency 'org.objenesis:objenesis' in project ':app'. Resolved versions for app (2.3) and test app (1.0) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

It seems that currently the only workaround is to put 

`configurations.all { 
  resolutionStrategy { force 'org.objenesis:objenesis:2.1' } 
}
`
 in your build.gradle

see more

**Comment by pakoito** [comment]
It seems like a project-specific issue to me. Would you have another dependency on your project that uses objenesis? Can you please post the output of your `gradle dependencies` task?

**Comment by danieldisu** [comment]
You are right, it was an older version of Mockito the one who was giving troubles!

Thanks 👍
