### ISSUE TITLE
Support for custom storage location?

### ISSUE THREAD

**Issue by itsJoKr** [pakoito/RxPaper2#7]
In PaperDb there is `Paper.bookOn(path)`. I don't see it accessible from RxPaper2.

I am using this for some caching, so would like to be able to do something like `RxPaper2.withPath(context.cacheDir))`.

**Comment by pakoito** [comment]
I checked and there's been no new release of PaperDB in a while, so maybe I missed wrapping that in one of the releases.

If you send a PR I can happily review, merge it, and cut a new release.

**Comment by itsJoKr** [comment]
Hey. Just note that there are 4 `with` methods because that is the number of permutations of 2 params (name and scheduler).

When adding another param (path), this would make it to 8 `with` methods and 4 private constructors. Some other approach (like builder) would make it nicer, but that would totally change the exposed API. So should I just go with 8 `with` methods?

**Comment by pakoito** [comment]
Yes, it seems reasonable to go with 8.

**Comment by pakoito** [comment]
Release 1.3.0 should be available with the change included now! Thanks @itsJoKr :D
